sudo: required
jdk: oraclejdk8

before_install: 
  - mkdir $HOME/.wurst/
  - cd $HOME/.wurst
  - sudo apt-get install -y wine

install:
  - wget http://peeeq.de/hudson/job/Wurst/lastSuccessfulBuild/artifact/downloads/wurstpack_compiler.zip
  - unzip -qq -n wurstpack_compiler.zip -d $HOME/.wurst

before_script: cd $TRAVIS_BUILD_DIR 

script:
  - java -jar $HOME/.wurst/wurstscript.jar $HOME/.wurst/common.j $HOME/.wurst/blizzard.j ./ -runcompiletimefunctions -runtests
