language: minimal

services:
  - docker

before_install:
  - docker pull frotty/wurstscript
  - docker run -it -d --name build frotty/wurstscript /bin/sh

install:
  - docker exec build grill install wurstscript
  - docker exec build git clone https://github.com/$TRAVIS_REPO_SLUG.git target
  - docker exec build /bin/sh -c "mv -v target/* target/.* . 2>/dev/null; true"
  - docker exec build git checkout -qf $TRAVIS_COMMIT

script:
  - docker exec build grill install
  - docker exec build grill test
